### ISSUE TITLE
Deal with variable length of SMILES

### ISSUE THREAD

**Issue by meandor** [DiscoverAI/sars-cov-2-drug-design#18]
**As a** researcher
**I want to** use smiles of a fixed length and see how long my smiles are
**so that** I have to do less data engineering in walter_white and can see what the current length of the first and last layer in my neural net in walter_white should be.

## Context
Pinkman is normalizing (feature engineering) the `moses.csv` dataset so it can be used by Walter White.
Walter White is responsible for training the generative model that learns from the normalized dataset from Pinkman.
In order to do so it would be easier for Walter White if the length of the input vector would be fixed (also for constructing the neural net architectures input and output layers).

## Tech hints
* calculate the max length of the SMILES
* pad the missing slots with `0`
* write out the `SMILES_length` to mlflow

### AC1
**GIVEN** the max SMILES length is 57
**WHEN** a SMILES has the length 57
**THEN** resulting SMILES should be exactly the same like it was before

### AC2
**GIVEN** the max SMILES length is 57
**WHEN** a SMILES has the length 25
**THEN** resulting SMILES should have the 26-57 (if started counting at 1) entry in the SMILES vector be padded with 0

### AC3
**GIVEN** mlflow is running and pinkman can run successfully in the saul_goodman pipeline and max SMILES length is 57
**WHEN** pinkman ran successfully
**THEN** the mlflow entry for pinkman should have the parameter `SMILES_length` set to 57 for that run

## Tasks
- [x] Create function that pads empty SMILES elements with `0.0`
- [x] Call function in `normalize` function
- [x] Set MLFlow entry for `SMILES_length`

**Comment by kelseymok** [comment]
Picking up after some initial work from @lauraniklas and @trepolus

**Comment by kelseymok** [comment]
@meandor do we ever expect a SMILE to be > 57 (erroneously)? If so, do we want to handle a failover case?

**Comment by kelseymok** [comment]
@meandor I assume you mean a double `0.0` as opposed to just `0` since the SMILES themselves get encoded to a Double

**Comment by meandor** [comment]
> @meandor do we ever expect a SMILE to be > 57 (erroneously)? If so, do we want to handle a failover case?

could be less or more, has to be dynamic
