### ISSUE TITLE
Base Security Setup for AWS

### ISSUE THREAD

**Issue by kelseymok** [DiscoverAI/sars-cov-2-drug-design#21]
# Background
We are currently using a fresh AWS account which needs some additional security around developers

# Tasks
- [x] Verify that we can't run in AWS Beach account
- [x] Create a developer role that allows flexible access but sets a permissions boundary
- [x] Create SNS topic to alert relevant user
- [x] Billing alert

**Comment by kelseymok** [comment]
The permissions boundary in the AWS Beach account doesn't let us tag IAM resources and doesn't seem to let us create a user with a permissions boundary (it should, but it's weirdly failing). Going to put all this on a personal account.

**Comment by kelseymok** [comment]
@meandor added you to the list of subscribers of the SNS topic -- you'll need to respond to the weird email from AWS (probably came through yesterday)
