### ISSUE TITLE
Refactor VPC setup for WalterWhite and EhrmanTraut

### ISSUE THREAD

**Issue by kelseymok** [DiscoverAI/sars-cov-2-drug-design#24]
# Background
Currently the VPC gets created in Walter White but the VPC is needed for EhrmanTraut as well which creates an awkward dependency route. We'll need to move the VPC out into its own CF stack and then use VPC exported values to redeploy WalterWhite and deploy (for the first time EhrmanTraut).

# Tasks
- [x] Create VPC stack in Sars-CoV and return outputs needed for WalterWhite
- [x] Use exported VPC values and redeploy WalterWhite ComputeEnvironment in one of the private subnets
- [x] Deploy EhrmanTraut into a EC2 Instance with a docker agent (don't forget to document how to port forward that, or figure out if it supports oauth)

**Comment by kelseymok** [comment]
@meandor took longer than expected! There were a few weird cloudformation things I had to suss out but I am able to get an EC2 instance up and running in the new VPC and can pull the image, but need to pass in the right vars (securely) and then make sure the networking is solid/secure/accessible via AWS Batch and things. Will have a look when I have time later.

For now, I've made sure that I've spun down the EC2 instance to reduce costs.

![image](https://user-images.githubusercontent.com/1141113/91347436-a3813300-e7e2-11ea-9b66-ac7230c5b4f5.png)

**Comment by kelseymok** [comment]
A new EC2 instance has been created (size `t2.medium` because `t2.small` doesn't have enough vCPU (1) to even show the UI (`t2.medium` has 2 vCPU) in a private subnet and the UI can be accessed by [PortForwarding via Systems Manager](https://aws.amazon.com/blogs/aws/new-port-forwarding-using-aws-system-manager-sessions-manager/) -- it's worth noting that this is the only way to view MLFLow since we have yet to think about authentication (or determine whether or not it's possible) and if it's worth doing. 

As a result of this now being deployed, the WalterWhite Job is now able to run and report to MLFlow (reachable at `ehrmantraut.sars-cov-2.local`, which is a private DNS record for the VPC):
![image](https://user-images.githubusercontent.com/1141113/91641200-1678ec80-ea23-11ea-90ab-3b6b92615b2c.png)

Will sync with @meandor to see if we can keep this running as it's roughly [$0.05 USD per hour](https://aws.amazon.com/ec2/pricing/on-demand/). Until then, will bring down the stack...

EDIT: Now running `t3.small` which is $0.024 per Hour
